# documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages
latex: true
warnings_are_errors: true

env:
  global:
    #- R_MAX_NUM_DLLS=999
    - _R_CHECK_FORCE_SUGGESTS_=true
    - _R_CHECK_CRAN_INCOMING_=true

jobs:
  include:
    - r: release
      r_binary_packages:
        - stringi
        - magrittr
        - curl
        - jsonlite
        - Rcpp
        - RcppEigen
        - openssl
        - utf8
        - gss
        - haven
        - minqa
        - mvtnorm
        - nloptr
        - SparseM
        - httpuv
        - markdown
        - sem
        - readxl
        - openxlsx
        - pander
        - git2r
        - data.table
      r_packages:
        - rlang
        - bindrcpp
        - tidyr
        - dplyr
        - coin
        - car
        - afex
        - jmv
        - WRS2
        - BH
        - remotes
      r_github_packages:
        - jimhester/lintr
        - r-lib/covr
    - r: devel
      r_binary_packages:
        - stringi
        - magrittr
        - curl
        - jsonlite
        - Rcpp
        - RcppEigen
        - openssl
        - utf8
        - gss
        - haven
        - minqa
        - mvtnorm
        - nloptr
        - SparseM
        - httpuv
        - markdown
        - sem
        - readxl
        - openxlsx
        - pander
        - git2r
        - data.table
      r_packages:
        - rlang
        - bindrcpp
        - tidyr
        - dplyr
        - coin
        - car
        - afex
        - jmv
        - WRS2
        - BH
        - remotes
      r_github_packages:
        - jimhester/lintr
        - r-lib/covr

addons:
  apt:
    packages:
      - libudunits2-dev
      - libgdal-dev
      - libproj-dev

before_install:
  - mkdir -p ~/.R
  - echo "CXX14FLAGS=-O3 -mtune=native -march=native -Wno-unused-variable -Wno-unused-function  -Wno-macro-redefined" >> ~/.R/Makevars
  - echo "CXX14=g++ -std=c++1y -fPIC" >> ~/.R/Makevars

notifications:
  email:
  on_success: change
  on_failure: change

after_success:
  - Rscript -e 'covr::codecov()'
  - Rscript -e 'covr::coveralls()'
  - R CMD INSTALL $PKG_TARBALL
  - Rscript -e 'lintr::lint_package()'