language: r
r:
  - release
  - devel
dist: trusty
latex: true
warnings_are_errors: TRUE

env:
  global:
    - _R_CHECK_FORCE_SUGGESTS_=true
    - _R_CHECK_CRAN_INCOMING_=true

cache: packages

repos:
  CRAN: https://cloud.r-project.org
  ropensci: http://packages.ropensci.org

# r_binary_packages:
#   - magrittr
#   - curl
#   - jsonlite
#   - rstan
#   - Rcpp
#   - RcppEigen
#   - openssl
#   - utf8
#   - gss
#   - haven
#   - minqa
#   - mvtnorm
#   - nloptr
#   - SparseM
#   - httpuv
#   - markdown
#   - pander
#   - git2r
#   - rlang
#   - bindrcpp
#   - tidyr
#   - dplyr
#   - rstantools
#   - bridgesampling
#   - BH
#   - stringi
#   - BayesFactor
#   - metaBMA
#   - coda
#   - coinmp
#   - pbkrtest
#   - mc2d
#   - data.table
#
# r_packages:
#   - remotes
#   - knitr
#   - rmarkdown

r_github_packages:
  - jimhester/lintr
  - r-lib/covr

addons:
  apt:
    packages:
      - libudunits2-dev
      - libgdal-dev
      - libproj-dev
      - libmpfr-dev

before_install:
  - mkdir -p ~/.R
  - echo "CXX14FLAGS=-O3 -mtune=native -march=native -Wno-unused-variable -Wno-unused-function  -Wno-macro-redefined" >> ~/.R/Makevars
  - echo "CXX14=g++ -std=c++1y -fPIC" >> ~/.R/Makevars

notifications:
  email:
  on_success: change
  on_failure: change

after_success:
  - Rscript -e 'covr::codecov()'
  - Rscript -e 'covr::coveralls()'
  - R CMD INSTALL $PKG_TARBALL
  - Rscript -e 'lintr::lint_package()'
